apiVersion: v1
kind: Service
metadata:
  name: sandbox
  namespace: difyaiv1114
spec:
  ports:
  - port: 8194
    targetPort: 8194
    protocol: TCP
    name: sandbox-port
  type: NodePort
  selector:
    app: sandbox