apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: difyai
spec:
  selector:
    app: postgres
  type: NodePort
  ports:
    - name: postgres-port
      protocol: TCP
      targetPort: 5432
      port: 5432
