apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: difyai
spec:
  selector:
    matchLabels:
      app: postgres
  serviceName: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      nodeSelector:
        kubernetes.io/hostname: node1
      containers:
        - name: postgres
          image: 192.168.44.130:5000/postgres:15-alpine
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: difyai-config
          ports:
            - name: postgres-port
              protocol: TCP
              containerPort: 5432
          resources:
            limits:
              cpu: 100m
              memory: 300Mi
            requests:
              cpu: 100m
              memory: 100Mi
          livenessProbe:
            exec:
              command: [ "pg_isready" ]
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 10
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: db-data
      volumes:
        - name: db-data
          hostPath:
            path: /root/dify/storage/v1.7.1/pgsql       # 节点上的真实目录
            type: DirectoryOrCreate
