apiVersion: v1
kind: Service
metadata:
  name: weaviate
  namespace: difyai
spec:
  selector:
    app: weaviate
  type: NodePort
  ports:
  - name: weaviate-port
    protocol: TCP
    port: 8080
    targetPort: 8080