apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: difyai
  name: difyai-k8s
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: longhorn
