apiVersion: v1
kind: Service
metadata:
  name: ssrf
  namespace: difyai
spec:
  type: NodePort
  selector:
    app: ssrf
  ports:
  - protocol: TCP
    port: 3128
    targetPort: 3128
    name: ssrf-port