apiVersion: v1
kind: Service
metadata:
  name: worker
  namespace: difyai
spec:
  ports:
  - protocol: TCP
    port: 5001
    targetPort: 5001
    name: worker-port
  selector:
    app: worker
  type: NodePort