apiVersion: v1
kind: Service
metadata:
  name: plugin-daemon
  namespace: difyai
spec:
  type: NodePort
  selector:
    app: plugin-daemon
  ports:
  - port: 5003
    targetPort: 5003
    protocol: TCP
    name: debug-port
  - port: 5002
    targetPort: 5002
    protocol: TCP
    name: service-port