apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: difyai
spec:
  selector:
    app: redis
  type: NodePort
  ports:
  - name: redis-port
    protocol: TCP
    port: 6379
    targetPort: 6379