apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: difyai
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      restartPolicy: Always
      containers:
      - name: web
        image: 'docker.m.daocloud.io/langgenius/dify-web:1.7.0'
        imagePullPolicy: IfNotPresent
        envFrom:
          - configMapRef:
              name: difyai-config
        env:
        - name: SENTRY_DSN
          valueFrom:
            configMapKeyRef:
              name: difyai-config
              key: WEB_SENTRY_DSN
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: 100m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 0.5Gi