apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: difyai
spec:
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: web-port
  type: NodePort
  selector:
    app: web